version: '3'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: angularProject1234
      MYSQL_DATABASE: biblio_tech_db
      MYSQL_USER: biblio_tech_user
      MYSQL_PASSWORD: biblio_tech_password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
